controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\SubscripeForm;
use app\models\Candidates;
use app\models\Questions;
use app\models\TestForm;
use app\models\TestResult;
use app\models\Settings;
use app\models\Checkingstarttest;
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout','about'],
                'rules' => [
                    [
                        'actions' => ['logout','about'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $model = new SubscripeForm();
        if(Yii::$app->request->isPost && $model->load(Yii::$app->request->post()) && $model->validate()){
            if($model->subscripe()){
                Yii::$app->session->setFlash('success', "Линк на тест отправлено"); 
            }else{
                Yii::$app->session->setFlash('error', "Ошибка!");
            }
        }
        return $this->render('index',['model'=>$model]);
    }
    public function actionStartTest($candidate = 0){
        if($candidate){
            $user = Candidates::find()->where(['link_test'=>$candidate])->one();
            $model = new TestForm();
            if(Yii::$app->request->isPost){

                $settings = Settings::find()->one();
                $checkingTest = Checkingstarttest::find()->where(['member_id'=>$user->id])->one();
                if(empty($checkingTest)){
                    $checkingTest = new Checkingstarttest();
                    $checkingTest->member_id = $user->id;
                    $checkingTest->start_time = time();
                    $checkingTest->end_time = 0;
                    $checkingTest->save();
                }else{
                    $checkingTest->start_time = time();
                    $checkingTest->end_time = 0;
                    $checkingTest->save();
                }
                $questions = Questions::find()->where(['status'=>1])->limit($settings->count_question)->all();
                return $this->render('test',['questions'=>$questions,'user'=>$user,'settings'=>$settings]);
            }else{
                return $this->render('testStart',['user'=>$user]);    
            }
            
        }else{
            return $this->redirect(['index']);
        }
    }
    public function actionResult(){
        if(isset($_POST['results']))
        {
            $session = Yii::$app->session;
            
            $resutls = $_POST['results'];
            $true = 0;
            $wrong = 0;
            $ball = 0;
            $maxBall = 0;
            foreach($resutls as $one)
            {
                $dvide = explode('-', $one);
                $question = Questions::findOne(intval($dvide[0]));
                if($question){
                    if(isset($dvide[1])){
                        if($question->getTrueAnswers(intval($dvide[1]))){
                            $true++;
                            $ball = $ball + $question->complexity;
                        }
                        else 
                            $wrong++;
                    }
                    else 
                        $wrong++;
                    $maxBall = $maxBall + $question->complexity;
                }else{
                    $wrong++;
                }
                
            }
            $res = ($ball > 0) ? ($ball*100)/($maxBall) : 0;
            $user = Candidates::find()->where(['email'=>$_POST['user']])->one();
            $user->result = $res;
            if($user->available_count_test == 0)
                $user->created_at = time();
            
            $user->save(false);
            $checkingTest = Checkingstarttest::find()->where(['member_id'=>$user->id])->one();
            $checkingTest->end_time = time();
            $checkingTest->save();

            $resultUser = new TestResult();
            $resultUser->member_id = $user->id;
            $resultUser->result = $res;
            $resultUser->true_answer = $true;
            $resultUser->wrong_answer = $wrong;
            $resultUser->save();
            $log = [];
            try {
                
                Yii::$app->mailer->compose()
                    ->setTo($user->email)
                    ->setFrom(['ilsweb@mail.ru' => 'Admin'])
                    ->setReplyTo([$user->email => 'Участник'])
                    ->setSubject('Результат теста')
                    ->setHtmlBody($this->getResultHtml($true,$wrong,$res, time()))
                    ->send();
            } catch (\Exception $e) {
                $log = $e;
            }
            // echo $true.' '.$wrong; die;
            return $this->render('test_result',['ball'=>$true,'maillog'=>$log]);
        }
    }
    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    public function getResultHtml($true = 0, $wrong = 0, $ball = 0, $resultDate){
        return '<table border = "1">
                    <thead>
                      <tr>
                        <td align="center" >Правильных ответов</td>
                        <td align="center" >Неправильных ответов</td>
                        <td align="center" >Балл</td>
                        <td align="center" >Дата сдачи</td>
                      </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>'.$true.'</td>
                            <td>'.$wrong.'</td>
                            <td> '.$ball.'%</td>
                            <td>'.date("d.m.Y H:i",$resultDate).'</td>
                        </tr>
                    </tbody>
                </table>';
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
//use yii\captcha\Captcha;
$this->title = 'TEST';
?>
<div class="site-index">

    <div class="jumbotron">
        <div class="row">
            <?= date('d.m.Y H:i:s', 1560807120); ?>
        </div>
    </div>
</div>
<style type="text/css">
    .centerBlock{
        float: none;
        margin: 0 auto;
    }
</style>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login center-block">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>
</div>

views/site/test.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
$time = $settings->test_time*60;
$scriptchangeblog = <<< JS
		/*$('#test_timer').countDown({
            targetOffset: {
              'day': 0,
              'month': 0,
              'year': 0,
              'hour': 0,
              'min': 0,
              'sec': $time,
            },
            omitWeeks: true,
                        
            // startTime: '01:12:12:00';
            // onComplete function
            onComplete: function() {
              $("#test-form").submit();
            }
        });*/
        var austDay = new Date();
		austDay.setSeconds(austDay.getSeconds() + $time); 
		
		$('#defaultCountdown').countdown({until: austDay,  
	    onExpiry: liftOff, onTick: watchCountdown});

		function liftOff() { 
		    $("#test-form").submit(); 
		} 
		 
		function watchCountdown(periods) {
			// console.log(periods);
		    /*$('#year').text('Just ' + periods[5] + ' minutes and ' + 
		        periods[6] + ' seconds to go');*/ 
		}
JS;
$this->registerJs($scriptchangeblog, yii\web\View::POS_READY);
?>

<div class="row">
	<h2>Участник <?= $user->email?> </h2>
	<div class="col-md-2">
		<!-- <div class="timer_block" id="test_timer" align="center">
			        <div id="timer_fixer">
			          <div class="dash hours_dash">
			            <span class="dash_title">Час</span> 
			            <div class="digit">0</div>
			            <div class="digit">0</div>
			          </div>
		
			          <div class="dash minutes_dash">
			            <span class="dash_title">Мин</span>
			            <div class="digit">0</div>
			            <div class="digit">0</div>
			          </div>
		
			          <div class="dash seconds_dash">
			            <span class="dash_title">Сек</span> 
			            <div class="digit">0</div>
			            <div class="digit">0</div>
			          </div>
		
			        </div>
		      	</div>	 -->
		<div id="defaultCountdown" style="min-height: 57px;"></div>
	</div>
	
	<?php $form = ActiveForm::begin([ 
		'action'=>\yii\helpers\Url::to(['/site/result']), 
		'options'=>['class'=>'form-horizontal'],
		'id'=>'test-form'
	]); ?>
			<input type="hidden" name="user" value="<?= $user->email?>">
			<input type="hidden" id="cq" value="<?= count($questions)?>">
			<div class="box visible" style="display: block;">
										      <!-- math tab -->
		      	<div class="test_tabs">
		      		<h2 class="test_navi">
		      			Вопрос 1
			        </h2>
			        <!-- test navigator -->
			        <hr class="gray_line">
					<?php $i = 0; foreach($questions as $test):?>
				        <!-- test box -->
				        <div class="test_box  <?= ($i==0)?'visible':''?> "  id="a<?php echo $test->id?>" data-p=<?= $i+1; ?>>
				          <!-- test title -->
			          		<h3 class="test_title">
					          	<input class="result_id" data-question = '<?= $test->id?>' type="hidden" name='results[]' data-ch=<?=$i+1;?> value="">
					            <!-- <span></span> -->
					            <div class="container">
					            	<?= $test->newTitle?>
					            	<span style="float: right; font-weight: bold;">Сложность <?= $test->complexity ?></span>
					            </div>
				          	</h3>
				          <!-- test variants -->
				          <ul class="test_variants">
				          <?php $k = "A"; foreach($test->answers as $a):?>
				            <li><a href="#" data-option="<?php echo $a->id;?>"><div><?= $k?></div><span><?= $a->newTitle?></span></a></li>
				           <?php $k++; endforeach;?>
				          </ul>
				        </div>
				        <!-- test box end -->
			    	<?php $i++; endforeach;?>
		      	</div>
			      <!-- math tab end -->
				<div align="center" class="login_button" style="margin-top: 106px;">
					<a class="button pq" data-id='1' style="display:none"><span class="glyphicon glyphicon-chevron-left"></span> Вернуться</a>
					<a class="button nq" data-id='1' style="margin-right:22px">Продолжить <span class="glyphicon glyphicon-chevron-right"></span></i> </a>
			      	
			    </div>
			    <div style="clear: both;">
			    	
			    </div>
			    <div align="center" class="login_button" style="margin-top: 25px;" >
			      <input type="submit" class="button" value="Завершить тест">
			      		
			    </div>
		 	</div>
	<?php ActiveForm::end(); ?>
</div>

views/site/testStart.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'TEST';
?>
<div class="site-index">

    <div class="jumbotron">
    		<?php if($user->created_at >= time()): ?>
    			<h3>Уважаемый кандидат!<br>
Приветствуем ваше желание пройти тест.<br>
Желаем удачи.</h3>
			 	<?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>
    			 	<div class="form-group">
                        <?= Html::submitButton('Начать тестирование', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>
			<?php else: ?>
	            <div class="row">
	                <h3>Ссылка не активна. Вы не можете участвовать в тестировании</h3>
	            </div>
        	<?php endif;?>
    </div>
</div>
<style type="text/css">
    .centerBlock{
        float: none;
        margin: 0 auto;
    }
</style>

views/site/test_result.php
<?php

$this->title = 'Резултать теста';
?>
<div class="site-index">

    <div class="jumbotron">
    	<?php if($maillog): ?>
    		<h3>спасибо за ваше участие</h3>
    		<p>Ошибка отправки результата на вашу почту</p>
		<?php else:?>
        <div class="row centerBlock">
            <h3>спасибо за ваше участие</h3>
        </div>
    	<?php endif;?>
    </div>
</div>
<style type="text/css">
    .centerBlock{
        float: none;
        margin: 0 auto;
    }
</style>

views/site/tmp.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
//use yii\captcha\Captcha;
$this->title = 'TEST';
?>
<div class="site-index">

    <div class="jumbotron">
        <div class="row">
            <?= date('d.m.Y H:i:s', 1560807120); ?>
        </div>
        <div class="row">
            <div class="col-md-6 centerBlock">
                 <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>


                    <?= $form->field($model, 'email') ?>


                    <?php /* $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ])*/ ?>

                    <div class="form-group">
                        <?= Html::submitButton('Send test link', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>
            </div>
        </div>
       
    </div>
</div>
<style type="text/css">
    .centerBlock{
        float: none;
        margin: 0 auto;
    }
</style>